/**
 * Demo mode fixtures.
 *
 * DEMO_GRANTS is a snapshot of real Grants.gov opportunities (fetched from the
 * live API — see /docs/ARCHITECTURE.md). DEMO_ORG is a realistic composite of
 * the small workforce-development nonprofits Granted is built for. The demo
 * proposal below was generated by the same Claude pipeline that runs live and
 * is replayed with realistic pacing when no API key is configured, so the
 * product is fully explorable before you bring your own key.
 */

import demoGrantsJson from "./demo-grants.json";
import type {
  GrantDetail,
  OrgProfile,
  Proposal,
  ReviewNote,
} from "./types";
import type { Plan } from "./ai/schemas";

export const DEMO_GRANTS = demoGrantsJson as GrantDetail[];

/** The featured demo flow drafts against this opportunity (BJA Second Chance Act). */
export const FEATURED_DEMO_GRANT_ID = "363637";

export const DEMO_ORG: OrgProfile = {
  name: "Brightpath Youth Alliance",
  tagline: "Paid job training and reentry support for opportunity youth in central Ohio.",
  mission:
    "Brightpath Youth Alliance helps young people ages 16–24 who are disconnected from school and work — including justice-involved youth — build lasting careers through paid workforce training, one-on-one mentorship, and industry-recognized credentials.",
  focusAreas: [
    "youth workforce development",
    "reentry and justice-involved youth",
    "career pathways and credentials",
    "mentorship",
  ],
  fundingCategories: ["ELT", "ED", "LJL", "ISS"],
  orgType: "nonprofit_501c3",
  annualBudgetUsd: 1_200_000,
  staffCount: 11,
  city: "Columbus",
  state: "OH",
  yearFounded: 2016,
  programs: [
    "CareerLaunch: a 12-week paid workforce training program in construction trades and logistics, ending in an OSHA-10 credential and direct employer placement.",
    "Second Shift: reentry navigation and employment placement for justice-involved young adults, run in partnership with the Franklin County juvenile court and two adult probation offices.",
    "Mentor Network: one-on-one volunteer mentors matched with every enrolled participant for 12 months.",
  ],
  achievements: [
    "Served 340 youth in 2025 across all programs.",
    "78% program completion rate; 92% of completers earned an industry-recognized credential.",
    "64% of completers placed in jobs paying $18/hour or more within 90 days.",
    "Recidivism among Second Shift completers is 11%, versus a 32% baseline for comparable young adults in Franklin County.",
  ],
  populationsServed: [
    "opportunity youth ages 16–24",
    "justice-involved young adults",
    "youth aging out of foster care",
  ],
  grantHistory:
    "City of Columbus CDBG subaward ($85,000, 2024–25); United Way of Central Ohio ($40,000/yr). No federal awards to date.",
};

/** Sample freeform text for the "paste your mission" onboarding path. */
export const DEMO_FREEFORM = `Brightpath Youth Alliance (Columbus, Ohio, founded 2016) is a 501(c)(3) nonprofit helping young people ages 16–24 who are disconnected from school and work — including justice-involved youth — build lasting careers.

Our programs: CareerLaunch, a 12-week paid workforce training program in construction trades and logistics ending in an OSHA-10 credential and direct employer placement. Second Shift, reentry navigation and employment placement for justice-involved young adults, in partnership with the Franklin County juvenile court and two adult probation offices. Mentor Network, one-on-one volunteer mentors matched with every participant for 12 months.

In 2025 we served 340 youth. 78% completed their program, 92% of completers earned an industry-recognized credential, and 64% were placed in jobs paying $18/hour or more within 90 days. Recidivism among Second Shift completers is 11%, versus a 32% county baseline.

We operate on a $1.2M annual budget with 11 staff. Past funding: City of Columbus CDBG subaward ($85,000), United Way of Central Ohio ($40,000/yr). We have not yet won a federal grant.`;

// ---------------------------------------------------------------------------
// Pre-generated drafting run for the featured grant (replayed in demo mode).
// ---------------------------------------------------------------------------

export const DEMO_PLAN: Plan = {
  proposalTitle: "Second Shift Expanded: Education-to-Employment Pathways for Reentering Youth in Central Ohio",
  strategy:
    "BJA is buying three things in this notice: credentialed vocational training aligned to the local job market, measurable job placement and retention, and reduced recidivism. Brightpath already runs exactly this model and — unusually for an applicant this size — has a recidivism number that beats the county baseline by 21 points. The through-line: don't propose a new program, propose scaling a proven one into the jail-to-community transition window BJA cares about, with the court partnership as the credibility anchor.",
  sections: [
    {
      id: "executive_summary",
      title: "Executive Summary",
      guidance: "State the ask, the model, and the three headline outcomes in under 200 words. Lead with the 11% vs 32% recidivism result.",
      wordTarget: 180,
    },
    {
      id: "statement_of_need",
      title: "Statement of Need",
      guidance: "Ground the need in Franklin County: young adults leaving confinement without credentials or employment. Mirror BJA's language on education, employment attainment, and retention.",
      wordTarget: 320,
    },
    {
      id: "project_design",
      title: "Project Design and Implementation",
      guidance: "Scale Second Shift: in-facility enrollment, CareerLaunch training with OSHA-10, placement, 12-month mentorship. Map each element to the NOFO's purpose language.",
      wordTarget: 430,
    },
    {
      id: "goals_outcomes",
      title: "Goals, Objectives, and Outcomes",
      guidance: "Three goals with numeric targets drawn from Brightpath's actual 2025 performance, scaled responsibly.",
      wordTarget: 280,
    },
    {
      id: "organizational_capacity",
      title: "Organizational Capacity",
      guidance: "Answer the capacity question head-on: court partnership, employer network, delivery record, and a named plan for federal grants management as a first-time federal grantee.",
      wordTarget: 300,
    },
    {
      id: "evaluation_plan",
      title: "Evaluation and Data Plan",
      guidance: "Recidivism tracking via county partners, employment verification, quarterly performance measures aligned to BJA's reporting.",
      wordTarget: 240,
    },
    {
      id: "budget_narrative",
      title: "Budget Narrative",
      guidance: "High-level allocation of a $985,000 request over 3 years; personnel-heavy is fine, justify participant wages as programmatic.",
      wordTarget: 230,
    },
  ],
};

/** First-draft content — statement_of_need is deliberately the weaker section the Reviewer flags. */
export const DEMO_SECTIONS_V1: Record<string, string> = {
  executive_summary: `Brightpath Youth Alliance requests $985,000 over three years under the FY 2026 Second Chance Act Improving Reentry Education and Employment Outcomes program to expand Second Shift, our education-to-employment pathway for justice-involved young adults in Franklin County, Ohio.

Second Shift is not a concept: it is a running program with a court partnership and results. Among 2025 completers, recidivism was 11% against a 32% baseline for comparable young adults in Franklin County. 92% of completers earned an industry-recognized credential, and 64% were placed in jobs paying $18/hour or more within 90 days of finishing.

With BJA support, Brightpath will extend Second Shift into the pre-release window at two partner facilities, enroll 270 reentering young adults over three years, and connect each to paid vocational training, an OSHA-10 credential, direct employer placement in construction and logistics, and a 12-month mentor. The project directly advances BJA's goals for this program: improved job readiness, employment attainment and retention, and reduced recidivism.`,

  statement_of_need: `Young people returning from confinement face steep barriers to stability. Nationally, formerly incarcerated people experience unemployment at rates far above the general population, and those without credentials fare worst. Employment is one of the strongest predictors of successful reentry, yet most young adults leave custody with no credential, no work history, and no adult in their corner.

Franklin County is no exception. Hundreds of young adults return to Columbus neighborhoods from confinement each year, most without a diploma-connected credential or a job lined up. The county's young-adult recidivism baseline of 32% reflects what happens when the transition window is left unsupported.

The need is not for another training program in general: it is for training connected to the moment of release. Brightpath's intake data shows that participants who enroll within 30 days of release complete at higher rates than those who find us months later. Today there is no systematic bridge between Franklin County facilities and workforce programming — referrals are informal, and young people fall through the gap between systems.

BJA's own framing of this opportunity — improving academic and vocational programs available to youth in confinement and expanding workforce development that results in job readiness, employment attainment, and retention — describes precisely the gap Second Shift Expanded is built to close.`,

  project_design: `Second Shift Expanded scales a working model across the full transition window, in four connected stages that track BJA's program goals.

**Stage 1: Pre-release enrollment (days −60 to 0).** Brightpath reentry navigators will hold weekly enrollment sessions at two partner facilities, in coordination with the Franklin County juvenile court and adult probation offices we already work with. Each enrollee completes an individualized education and employment plan before release — the plan BJA's notice asks applicants to center.

**Stage 2: Paid vocational training (weeks 1–12).** Within 30 days of release, participants enter CareerLaunch, our 12-week paid training program in construction trades and logistics. Participants earn while they train — removing the survival-income pressure that pushes reentering young adults back toward instability — and finish with an OSHA-10 credential. Training content aligns to the central Ohio labor market, where construction and logistics employers face persistent entry-level shortages.

**Stage 3: Direct placement (by week 16).** Brightpath placement staff match completers with employer partners for interviews before graduation. Our 2025 placement rate — 64% of completers in jobs paying $18/hour or more within 90 days — is the program's proof of concept; this project sets a 65% target at expanded scale.

**Stage 4: Retention mentorship (months 1–12).** Every participant is matched with a trained volunteer mentor for 12 months, with structured monthly check-ins covering employment retention, court obligations, and next credentials. Mentorship is Brightpath's retention engine and the mechanism behind our 11% completer recidivism rate.

Across three years the project will enroll 270 reentering young adults (60 in year one, then 105 per year), with enrollment capacity phased to match new navigator hiring. [ADD: names and letters of commitment for the two partner facilities.]`,

  goals_outcomes: `**Goal 1: Connect reentering young adults to education and employment pathways.** Objectives: enroll 270 justice-involved young adults ages 16–24 over 36 months; 100% complete an individualized education and employment plan before or within 30 days of release; 75% complete CareerLaunch training (2025 actual: 78%).

**Goal 2: Improve credential attainment, employment attainment, and retention.** Objectives: 85% of completers earn an OSHA-10 or equivalent industry-recognized credential (2025 actual: 92%); 65% of completers placed in employment paying $18/hour or more within 90 days (2025 actual: 64%); 70% of placed participants employed at 6 months post-placement.

**Goal 3: Reduce recidivism among participants.** Objective: hold participant recidivism at or below 15% at 12 months post-release, measured against the 32% county baseline via our data-sharing arrangement with Franklin County partners.

Targets are set from Brightpath's actual 2025 performance, adjusted conservatively for the harder-to-serve pre-release population this project adds. Each objective maps to a BJA performance measure and will be reported quarterly through JustGrants.`,

  organizational_capacity: `Brightpath Youth Alliance has run workforce programming for opportunity youth in Columbus since 2016 and reentry-focused programming since 2021. The organization operates on a $1.2M annual budget with 11 staff, and served 340 young people in 2025.

Three capacities matter for this project. First, the court relationship: Second Shift operates in active partnership with the Franklin County juvenile court and two adult probation offices, which refer participants and share outcome data — the institutional plumbing a pre-release program requires. Second, the employer network: CareerLaunch places completers directly with construction and logistics employers, and our $18/hour placement floor reflects real demand, not aspiration. Third, delivery discipline: a 78% completion rate and 92% credential attainment among completers demonstrate that Brightpath can execute the model this proposal scales.

We are direct about being a first-time federal grantee. To manage that transition responsibly, this budget funds a part-time grants manager dedicated to federal compliance, and Brightpath will contract with [ADD: name of fiscal/compliance consultant, if engaged] for JustGrants reporting setup in the first 90 days. Our finance function already administers a federal pass-through (City of Columbus CDBG subaward), giving us working familiarity with federal cost principles.`,

  evaluation_plan: `Evaluation serves two purposes: BJA accountability and program learning.

**Performance measurement.** Brightpath will report BJA's required performance measures quarterly through JustGrants. Enrollment, plan completion, training completion, credential attainment, placement, wage at placement, and 6-month retention are captured in our case-management system at the participant level, with employment verified through employer confirmation and pay documentation.

**Recidivism measurement.** Reconviction and reincarceration data for participants will be tracked at 6, 12, and 24 months post-release under our existing data-sharing arrangement with Franklin County partners, benchmarked against the county's young-adult baseline.

**Learning.** A third-party evaluator [ADD: evaluator name or procurement plan] will conduct an annual implementation review — enrollment timing, dosage, and mentorship engagement — so the model improves during the grant period rather than after it. Findings will be shared with BJA and with the National Reentry Resource Center's practitioner network.`,

  budget_narrative: `Brightpath requests $985,000 over 36 months. The allocation reflects a personnel-driven direct-service model.

**Personnel and fringe (58%, ~$571,000).** Two full-time reentry navigators (new hires, facility-based enrollment and case management), 0.5 FTE placement coordinator, 0.25 FTE grants manager (federal compliance and JustGrants reporting), and a share of the program director's time.

**Participant training wages and supports (24%, ~$236,000).** Paid training stipends for 270 participants during CareerLaunch, plus transportation and work-readiness supports (tools, boots, licensure fees). Participant wages are programmatic, not administrative: paid training is the mechanism that makes enrollment viable for young adults under survival-income pressure.

**Training delivery and credentialing (10%, ~$99,000).** OSHA-10 certification costs, instructor time, and facility-based pre-release orientation materials.

**Evaluation, travel, and indirect (8%, ~$79,000).** Third-party evaluation contract, required BJA conference travel, and indirect costs at Brightpath's de minimis rate.

A detailed line-item budget and justification accompany this narrative as required attachments.`,
};

export const DEMO_REVIEW_NOTES: ReviewNote[] = [
  {
    sectionId: "statement_of_need",
    severity: "critical",
    issue:
      "The need statement leans on national framing and asserts 'hundreds of young adults return each year' without a sourced local figure. BJA panels score localized, quantified need; an unsourced estimate reads as a placeholder.",
    fix: "Anchor the section in specific Franklin County data — annual releases of 16–24-year-olds, credential rates at exit — with sources, and cut the generic national opening.",
  },
  {
    sectionId: "statement_of_need",
    severity: "important",
    issue: "The strongest evidence in the application (the 30-day enrollment window insight from intake data) is buried in the third paragraph.",
    fix: "Lead the local analysis with the enrollment-timing finding — it is the applicant's own data and directly justifies the pre-release design.",
  },
  {
    sectionId: "project_design",
    severity: "important",
    issue: "Facility partners are unnamed ([ADD] placeholder). Panels will not award pre-release programming without named facilities and letters of commitment.",
    fix: "Name both facilities and reference attached letters of commitment before submission.",
  },
  {
    sectionId: "budget_narrative",
    severity: "polish",
    issue: "The de minimis indirect rate is mentioned without the percentage.",
    fix: "State the 10% de minimis rate explicitly to preempt a budget-review question.",
  },
];

export const DEMO_SCORE_BEFORE = 74;
export const DEMO_SCORE_AFTER = 88;

/** Revised statement_of_need after the Reviewer's notes. */
export const DEMO_REVISED_SECTIONS: Record<string, string> = {
  statement_of_need: `In Franklin County, the transition from confinement to community is where young people are lost. [ADD: exact count from Franklin County partners] young adults ages 16–24 were released from county juvenile and adult facilities in the most recent reporting year, the overwhelming majority without an industry-recognized credential or employment arranged at exit, per intake assessments shared by our court and probation partners. The county's 32% young-adult recidivism baseline is the measurable cost of that unsupported window.

Brightpath's own intake data sharpens the picture: participants who enroll in workforce programming within 30 days of release complete at meaningfully higher rates than those who reach us months later. Timing, not motivation, is the differentiator — yet no systematic bridge exists today between Franklin County facilities and workforce programming. Referrals are informal, waitlists ignore release dates, and young people fall through the gap between the justice and workforce systems in exactly the weeks that determine their trajectory.

The consequences track what BJA's notice targets: without credentials, without work history, and without an adult in their corner, reentering young adults cycle into unemployment and back into the system. Employment is among the strongest predictors of successful reentry, and employment at a family-sustaining wage — the $18/hour floor Brightpath builds placements around — is what makes desistance durable.

This opportunity's stated goal — improving vocational programs available to youth in confinement and expanding workforce development that produces job readiness, employment attainment, and retention — describes the precise gap in Franklin County's system. Second Shift Expanded closes it at the source: enrollment before release, paid training within 30 days, and a credential, a job, and a mentor on the other side.`,
};

export function buildDemoProposal(): Proposal {
  const sections = DEMO_PLAN.sections.map((s) => ({
    id: s.id,
    title: s.title,
    content: DEMO_REVISED_SECTIONS[s.id] ?? DEMO_SECTIONS_V1[s.id] ?? "",
  }));
  return {
    grantId: FEATURED_DEMO_GRANT_ID,
    grantTitle: "BJA FY 2026 Second Chance Act Improving Reentry Education and Employment Outcomes",
    orgName: DEMO_ORG.name,
    title: DEMO_PLAN.proposalTitle,
    sections,
    reviewNotes: DEMO_REVIEW_NOTES,
    scoreBefore: DEMO_SCORE_BEFORE,
    scoreAfter: DEMO_SCORE_AFTER,
    generatedAt: new Date().toISOString(),
    engine: "demo",
  };
}
